### ISSUE TITLE
Add Filter "Beginner , Intermediate , Advanced"

### ISSUE THREAD

**Issue by antoniogarcia78** [revolunet/PythonBooks#30]
Is very useful.

**Comment by antoniogarcia78** [comment]
"Explore Flask" not working. Maybe you can use http://explore-flask.readthedocs.org/en/latest/

**Comment by jlamim** [comment]
I'm working in this issue.

**Comment by revolunet** [comment]
FYI there's a similar ongoing effort on the similar JSBook repo : https://github.com/revolunet/JSbooks/tree/newdesign

**Comment by jeremejazz** [comment]
👍 love the js books design

**Comment by jeremejazz** [comment]
I have tried implementing the filter function on my fork. Here is the [link ](https://jeremejazz.github.io/PythonBooks/) for the working demo. I'm not sure with the color though (not good in colors 😁. I based it on JSbooks site. Though this still requires some testing and fixes

**Comment by jeremejazz** [comment]
@antoniogarcia78 Feature has been added.
