### ISSUE TITLE
Kivy Link Broken

### ISSUE THREAD

**Issue by jeremejazz** [revolunet/PythonBooks#51]
The link to the Book [Kivy Programming Guide](https://kivy.org/docs/pdf/Kivy-latest.pdf) is currently not working.  
I have found an alternative link in readthedocs that might be using the latest version of kivy 1.10 https://media.readthedocs.org/pdf/kivy/latest/kivy.pdf

**Comment by Dawny33** [comment]
@jeremejazz Nice find.  Possible to send a PR with the updated link?

**Comment by jeremejazz** [comment]
@Dawny33  Sure I'm working on it now cheers

**Comment by jeremejazz** [comment]
I used https://readthedocs.org/projects/kivy/downloads/ instead for more ebook format options.

**Comment by jeremejazz** [comment]
Changes have been merged. now closing the issue :smile:
